# Generated by Django 5.0.7 on 2024-08-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dept', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('status', models.CharField(max_length=34)),
                ('domain', models.CharField(max_length=34)),
            ],
        ),
    ]
